--  UDTFWW
--
--  SQL WORD_WRAP UDTF
--
--  October 2023
--
--  Replace
--
--    $(SCHEMA) with the name of the schema to create
--                  the function.
--    $(PGM_LIB) with the library name of external program.

SET SCHEMA $(SCHEMA);

DROP SPECIFIC FUNCTION IF EXISTS WORD_WRAP;
DROP SPECIFIC FUNCTION IF EXISTS WORD_WRAP_WITH_LINE_FEED;

CREATE OR REPLACE FUNCTION
  WORD_WRAP
(
  text VARCHAR(8192),
  width SMALLINT
)
RETURNS TABLE
(
  line_number SMALLINT,
  line VARCHAR(1024)
)
LANGUAGE RPGLE
PARAMETER STYLE DB2SQL
SPECIFIC WORD_WRAP
NOT FENCED
DETERMINISTIC
NO SQL
RETURNS NULL ON NULL INPUT
EXTERNAL NAME '$(PGM_LIB)/WORDWRAP1'
DISALLOW PARALLEL
;

LABEL ON SPECIFIC FUNCTION
  WORD_WRAP
IS
  'WORD_WRAP UDTF'
;


CREATE OR REPLACE FUNCTION
  WORD_WRAP
(
  text VARCHAR(8192),
  width SMALLINT,
  line_feed_sym VARCHAR(5)
)
RETURNS TABLE
(
  line_number SMALLINT,
  line VARCHAR(1024)
)
LANGUAGE RPGLE
PARAMETER STYLE DB2SQL
SPECIFIC WORD_WRAP_WITH_LINE_FEED
NOT FENCED
DETERMINISTIC
NO SQL
RETURNS NULL ON NULL INPUT
EXTERNAL NAME '$(PGM_LIB)/WORDWRAP2'
DISALLOW PARALLEL
;

LABEL ON SPECIFIC FUNCTION
  WORD_WRAP_WITH_LINE_FEED
IS
  'WORD_WRAP UDTF (with line feed)'
;
